//------------------------------------------------------------------------------
// <auto-generated>
//     Questo codice è stato generato da uno strumento.
//
//     Le modifiche apportate a questo file possono causare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsLibrary
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://tempuri.org/")]
    public partial class Author : object
    {
        
        private long IdField;
        
        private string NameField;
        
        private string SurnameField;
        
        private string NationalityField;
        
        private System.DateTime DateOfBirthField;
        
        private WsLibrary.Book[] BooksField;
        
        private WsLibrary.Review[] ReviewsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Surname
        {
            get
            {
                return this.SurnameField;
            }
            set
            {
                this.SurnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nationality
        {
            get
            {
                return this.NationalityField;
            }
            set
            {
                this.NationalityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime DateOfBirth
        {
            get
            {
                return this.DateOfBirthField;
            }
            set
            {
                this.DateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public WsLibrary.Book[] Books
        {
            get
            {
                return this.BooksField;
            }
            set
            {
                this.BooksField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public WsLibrary.Review[] Reviews
        {
            get
            {
                return this.ReviewsField;
            }
            set
            {
                this.ReviewsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://tempuri.org/")]
    public partial class Book : object
    {
        
        private string IsbnField;
        
        private string TitleField;
        
        private int TotalPageField;
        
        private WsLibrary.BookData BookDataField;
        
        private WsLibrary.BookPrice[] PricesField;
        
        private WsLibrary.Review[] ReviewsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Isbn
        {
            get
            {
                return this.IsbnField;
            }
            set
            {
                this.IsbnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalPage
        {
            get
            {
                return this.TotalPageField;
            }
            set
            {
                this.TotalPageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WsLibrary.BookData BookData
        {
            get
            {
                return this.BookDataField;
            }
            set
            {
                this.BookDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public WsLibrary.BookPrice[] Prices
        {
            get
            {
                return this.PricesField;
            }
            set
            {
                this.PricesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public WsLibrary.Review[] Reviews
        {
            get
            {
                return this.ReviewsField;
            }
            set
            {
                this.ReviewsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://tempuri.org/")]
    public partial class Review : object
    {
        
        private long IdField;
        
        private System.DateTime DateField;
        
        private int VoteField;
        
        private string DescriptionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Vote
        {
            get
            {
                return this.VoteField;
            }
            set
            {
                this.VoteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookData", Namespace="http://tempuri.org/")]
    public partial class BookData : object
    {
        
        private string IsbnField;
        
        private string BookClassificationField;
        
        private string PublisherField;
        
        private System.DateTime PublicationDateField;
        
        private int TotalSoldField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Isbn
        {
            get
            {
                return this.IsbnField;
            }
            set
            {
                this.IsbnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BookClassification
        {
            get
            {
                return this.BookClassificationField;
            }
            set
            {
                this.BookClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Publisher
        {
            get
            {
                return this.PublisherField;
            }
            set
            {
                this.PublisherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime PublicationDate
        {
            get
            {
                return this.PublicationDateField;
            }
            set
            {
                this.PublicationDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int TotalSold
        {
            get
            {
                return this.TotalSoldField;
            }
            set
            {
                this.TotalSoldField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookPrice", Namespace="http://tempuri.org/")]
    public partial class BookPrice : object
    {
        
        private long IdField;
        
        private string DescriptionField;
        
        private double PriceField;
        
        private System.DateTime PriceStartDateField;
        
        private System.DateTime PriceEndDateField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime PriceStartDate
        {
            get
            {
                return this.PriceStartDateField;
            }
            set
            {
                this.PriceStartDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime PriceEndDate
        {
            get
            {
                return this.PriceEndDateField;
            }
            set
            {
                this.PriceEndDateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsLibrary.IService")]
    public interface IService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllAuthors", ReplyAction="*")]
        WsLibrary.Author[] GetAllAuthors();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAllAuthors", ReplyAction="*")]
        System.Threading.Tasks.Task<WsLibrary.Author[]> GetAllAuthorsAsync();
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento name dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAuthorByName", ReplyAction="*")]
        WsLibrary.GetAuthorByNameResponse GetAuthorByName(WsLibrary.GetAuthorByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAuthorByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WsLibrary.GetAuthorByNameResponse> GetAuthorByNameAsync(WsLibrary.GetAuthorByNameRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento GetAuthorByIdResult dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAuthorById", ReplyAction="*")]
        WsLibrary.GetAuthorByIdResponse GetAuthorById(WsLibrary.GetAuthorByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/GetAuthorById", ReplyAction="*")]
        System.Threading.Tasks.Task<WsLibrary.GetAuthorByIdResponse> GetAuthorByIdAsync(WsLibrary.GetAuthorByIdRequest request);
        
        // CODEGEN: Generazione del contratto di messaggio perché il nome di elemento author dello spazio dei nomi http://tempuri.org/ non è contrassegnato come nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertAuthor", ReplyAction="*")]
        WsLibrary.InsertAuthorResponse InsertAuthor(WsLibrary.InsertAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/InsertAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<WsLibrary.InsertAuthorResponse> InsertAuthorAsync(WsLibrary.InsertAuthorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorByName", Namespace="http://tempuri.org/", Order=0)]
        public WsLibrary.GetAuthorByNameRequestBody Body;
        
        public GetAuthorByNameRequest()
        {
        }
        
        public GetAuthorByNameRequest(WsLibrary.GetAuthorByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAuthorByNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetAuthorByNameRequestBody()
        {
        }
        
        public GetAuthorByNameRequestBody(string name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WsLibrary.GetAuthorByNameResponseBody Body;
        
        public GetAuthorByNameResponse()
        {
        }
        
        public GetAuthorByNameResponse(WsLibrary.GetAuthorByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAuthorByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public WsLibrary.Author[] GetAuthorByNameResult;
        
        public GetAuthorByNameResponseBody()
        {
        }
        
        public GetAuthorByNameResponseBody(WsLibrary.Author[] GetAuthorByNameResult)
        {
            this.GetAuthorByNameResult = GetAuthorByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorByIdRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorById", Namespace="http://tempuri.org/", Order=0)]
        public WsLibrary.GetAuthorByIdRequestBody Body;
        
        public GetAuthorByIdRequest()
        {
        }
        
        public GetAuthorByIdRequest(WsLibrary.GetAuthorByIdRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAuthorByIdRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long id;
        
        public GetAuthorByIdRequestBody()
        {
        }
        
        public GetAuthorByIdRequestBody(long id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAuthorByIdResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAuthorByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WsLibrary.GetAuthorByIdResponseBody Body;
        
        public GetAuthorByIdResponse()
        {
        }
        
        public GetAuthorByIdResponse(WsLibrary.GetAuthorByIdResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAuthorByIdResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsLibrary.Author GetAuthorByIdResult;
        
        public GetAuthorByIdResponseBody()
        {
        }
        
        public GetAuthorByIdResponseBody(WsLibrary.Author GetAuthorByIdResult)
        {
            this.GetAuthorByIdResult = GetAuthorByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAuthorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAuthor", Namespace="http://tempuri.org/", Order=0)]
        public WsLibrary.InsertAuthorRequestBody Body;
        
        public InsertAuthorRequest()
        {
        }
        
        public InsertAuthorRequest(WsLibrary.InsertAuthorRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAuthorRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsLibrary.Author author;
        
        public InsertAuthorRequestBody()
        {
        }
        
        public InsertAuthorRequestBody(WsLibrary.Author author)
        {
            this.author = author;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertAuthorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public WsLibrary.InsertAuthorResponseBody Body;
        
        public InsertAuthorResponse()
        {
        }
        
        public InsertAuthorResponse(WsLibrary.InsertAuthorResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertAuthorResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WsLibrary.Author InsertAuthorResult;
        
        public InsertAuthorResponseBody()
        {
        }
        
        public InsertAuthorResponseBody(WsLibrary.Author InsertAuthorResult)
        {
            this.InsertAuthorResult = InsertAuthorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServiceChannel : WsLibrary.IService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<WsLibrary.IService>, WsLibrary.IService
    {
        
        /// <summary>
        /// Implementare questo metodo parziale per configurare l'endpoint servizio.
        /// </summary>
        /// <param name="serviceEndpoint">Endpoint da configurare</param>
        /// <param name="clientCredentials">Credenziali del client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceClient() : 
                base(ServiceClient.GetDefaultBinding(), ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService_soap.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WsLibrary.Author[] GetAllAuthors()
        {
            return base.Channel.GetAllAuthors();
        }
        
        public System.Threading.Tasks.Task<WsLibrary.Author[]> GetAllAuthorsAsync()
        {
            return base.Channel.GetAllAuthorsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsLibrary.GetAuthorByNameResponse WsLibrary.IService.GetAuthorByName(WsLibrary.GetAuthorByNameRequest request)
        {
            return base.Channel.GetAuthorByName(request);
        }
        
        public WsLibrary.Author[] GetAuthorByName(string name)
        {
            WsLibrary.GetAuthorByNameRequest inValue = new WsLibrary.GetAuthorByNameRequest();
            inValue.Body = new WsLibrary.GetAuthorByNameRequestBody();
            inValue.Body.name = name;
            WsLibrary.GetAuthorByNameResponse retVal = ((WsLibrary.IService)(this)).GetAuthorByName(inValue);
            return retVal.Body.GetAuthorByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsLibrary.GetAuthorByNameResponse> WsLibrary.IService.GetAuthorByNameAsync(WsLibrary.GetAuthorByNameRequest request)
        {
            return base.Channel.GetAuthorByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsLibrary.GetAuthorByNameResponse> GetAuthorByNameAsync(string name)
        {
            WsLibrary.GetAuthorByNameRequest inValue = new WsLibrary.GetAuthorByNameRequest();
            inValue.Body = new WsLibrary.GetAuthorByNameRequestBody();
            inValue.Body.name = name;
            return ((WsLibrary.IService)(this)).GetAuthorByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsLibrary.GetAuthorByIdResponse WsLibrary.IService.GetAuthorById(WsLibrary.GetAuthorByIdRequest request)
        {
            return base.Channel.GetAuthorById(request);
        }
        
        public WsLibrary.Author GetAuthorById(long id)
        {
            WsLibrary.GetAuthorByIdRequest inValue = new WsLibrary.GetAuthorByIdRequest();
            inValue.Body = new WsLibrary.GetAuthorByIdRequestBody();
            inValue.Body.id = id;
            WsLibrary.GetAuthorByIdResponse retVal = ((WsLibrary.IService)(this)).GetAuthorById(inValue);
            return retVal.Body.GetAuthorByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsLibrary.GetAuthorByIdResponse> WsLibrary.IService.GetAuthorByIdAsync(WsLibrary.GetAuthorByIdRequest request)
        {
            return base.Channel.GetAuthorByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsLibrary.GetAuthorByIdResponse> GetAuthorByIdAsync(long id)
        {
            WsLibrary.GetAuthorByIdRequest inValue = new WsLibrary.GetAuthorByIdRequest();
            inValue.Body = new WsLibrary.GetAuthorByIdRequestBody();
            inValue.Body.id = id;
            return ((WsLibrary.IService)(this)).GetAuthorByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsLibrary.InsertAuthorResponse WsLibrary.IService.InsertAuthor(WsLibrary.InsertAuthorRequest request)
        {
            return base.Channel.InsertAuthor(request);
        }
        
        public WsLibrary.Author InsertAuthor(WsLibrary.Author author)
        {
            WsLibrary.InsertAuthorRequest inValue = new WsLibrary.InsertAuthorRequest();
            inValue.Body = new WsLibrary.InsertAuthorRequestBody();
            inValue.Body.author = author;
            WsLibrary.InsertAuthorResponse retVal = ((WsLibrary.IService)(this)).InsertAuthor(inValue);
            return retVal.Body.InsertAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WsLibrary.InsertAuthorResponse> WsLibrary.IService.InsertAuthorAsync(WsLibrary.InsertAuthorRequest request)
        {
            return base.Channel.InsertAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WsLibrary.InsertAuthorResponse> InsertAuthorAsync(WsLibrary.Author author)
        {
            WsLibrary.InsertAuthorRequest inValue = new WsLibrary.InsertAuthorRequest();
            inValue.Body = new WsLibrary.InsertAuthorRequestBody();
            inValue.Body.author = author;
            return ((WsLibrary.IService)(this)).InsertAuthorAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService_soap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService_soap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7141/Service.asmx");
            }
            throw new System.InvalidOperationException(string.Format("L\'endpoint denominato \'{0}\' non è stato trovato.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService_soap);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService_soap);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService_soap,
        }
    }
}
